### ISSUE TITLE
LightShark

### ISSUE THREAD

**Issue by eric-emc** [bitfocus/companion-module-equipson-lightshark#1]
Hi
It would be great to control the LightShark lighting controller over companion.
http://lightshark.es
It can be controlled via OSC:
https://www.eafg.es/productos/Docs/Manuales/LightShark_v1_20200401172050.3
(Page 103)

**Comment by JTF4** [comment]
Had to fix Joseph's spelling there.

**Comment by JTF4** [comment]
https://we.tl/t-MeXGUimuqe here's my build. Both windows and mac are in there.

**Comment by BenjaminM88** [comment]
> https://we.tl/t-MeXGUimuqe here's my build. Both windows and mac are in there.

@JTF4 Almost a year later… has your build been testet? Would love to get access to your build too. Could you upload it again?

**Comment by josephdadams** [comment]
@JTF4 lmk if you want me to tag a release and put it in betas

**Comment by JTF4** [comment]
Since it's all OSC, I think you can go ahead and put it in the beta. I'll go ahead and tag it

**Comment by josephdadams** [comment]
I added it
